name: release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - "v*" # 监听所有 tag 推送

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ESP-IDF build (espressif/esp-idf-ci-action)
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: latest
          target: esp32c3
          path: .
          command: idf.py build

      - name: Merge firmware
        run: python3 merge_bin.py

      - name: Upload merged bin to Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./build/c3Homekit_merged.bin
